"""A bumped source pin must not be able to leave the installed lock behind."""

import importlib.util
import tempfile
import unittest
from pathlib import Path

_SPEC = importlib.util.spec_from_file_location(
    "audio_lock", Path(__file__).with_name("audio-lock-check.py")
)
_MODULE = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(_MODULE)

LOCK_HEADER = """# This file was autogenerated by uv via the following command:
#    uv pip compile fork/audio_trial/requirements.in -o requirements.lock
"""


def write(directory: Path, source: str, lock: str) -> tuple[Path, Path]:
    source_path = directory / "requirements.in"
    lock_path = directory / "requirements.lock"
    source_path.write_text(source)
    lock_path.write_text(LOCK_HEADER + lock)
    return source_path, lock_path


class AudioLockTests(unittest.TestCase):
    def drift(self, source: str, lock: str) -> list[str]:
        with tempfile.TemporaryDirectory() as directory:
            return _MODULE.drift(*write(Path(directory), source, lock))

    def test_matching_versions_are_quiet(self):
        lock = "numpy==1.26.4 \\\n    --hash=sha256:abc\nsoxr==1.1.0 \\\n    --hash=sha256:def\n"
        self.assertEqual(self.drift("numpy==1.26.4\nsoxr==1.1.0\n", lock), [])

    def test_a_bumped_source_pin_is_reported(self):
        problems = self.drift(
            "numpy==1.27.0\n", "numpy==1.26.4 \\\n    --hash=sha256:abc\n"
        )
        self.assertEqual(len(problems), 1)
        self.assertIn("lock has 1.26.4", problems[0])

    def test_a_new_source_pin_missing_from_the_lock_is_reported(self):
        problems = self.drift("numpy==1.26.4\nsoxr==1.1.0\n", "numpy==1.26.4\n")
        self.assertEqual(len(problems), 1)
        self.assertIn("missing from the lock", problems[0])

    def test_names_compare_the_way_pypi_does(self):
        self.assertEqual(
            self.drift("Faster_Whisper==1.1.1\n", "faster-whisper==1.1.1\n"), []
        )

    def test_local_versions_match_their_public_part(self):
        self.assertEqual(self.drift("torch==2.8.0+cpu\n", "torch==2.8.0+cpu\n"), [])
        self.assertEqual(self.drift("torch==2.8.0\n", "torch==2.8.0+cpu\n"), [])

    def test_comments_and_options_are_ignored(self):
        lock = "# a comment\n--index-url https://example.invalid\nnumpy==1.26.4\n"
        self.assertEqual(self.drift("numpy==1.26.4  # pinned\n", lock), [])

    def test_the_repository_lock_is_current(self):
        trial = Path(__file__).resolve().parents[1] / "audio_trial"
        self.assertEqual(
            _MODULE.drift(trial / "requirements.in", trial / "requirements.lock"), []
        )


if __name__ == "__main__":
    unittest.main()
